config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
             registrations:      'users/registrations',
             omniauth_callbacks: 'users/omniauth_callbacks' }
  root 'items#index'
  get  'items/search_brand' => 'items#search_brand'
  resources :items, only: [:index, :new, :create, :show, :edit, :update] do
    resources :orders,  only: [:new, :create]
  end
  resources :categories, only: [:index, :show]
  delete 'items/:id' => 'items#destroy', as: :destroy_item
  resources :credits, only: [:index, :new, :create, :destroy]
  resources :listings, only: [:index]
  resources :users, only: [:new] do
    resources :userconfirms, only: [:new, :create]
    resources :addresses, only: [:new, :create]
    resources :sales_moneys, only: [:index]
    get 'sales_moneys/history' => 'sales_moneys#history', as: 'sales_moneys_history'
    get 'mypage' => 'users#mypage'
    get 'profile' => 'profiles#edit'
    patch 'profile' => 'profiles#update'
  end
  get 'logout' => 'users#logout' # ログアウトボタンがある画面への遷移
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  def index
    @items = Item.where(user_id: current_user.id).page(params[:page]).per(7).order("created_at DESC")
  end
end

app/views/listings/index.html.haml
= render './header'
= render './bread_crumb'
- if flash[:notice]
  .flash
    = flash[:notice]
.l-container-clearfix
  .right-content-items
    .auction_item_header
      %h2.title 出品した商品
    .auction_item_main
      %ul.auction_item_tabs
        %li.auction_item_tabs__list
          %h3.change_btn.is-active
            出品中
        %li.auction_item_tabs__list
          %h3.change_btn
            取引中
        %li.auction_item_tabs__list
          %h3.change_btn
            売却済み

      .tab-contents
        - if @items.present?
          - @items.each do |item|
            .item-list
              = image_tag "#{item.item_images[0].item_image_src}", size: "50x50", class: "item-image"
              .item-name
                = item.item_name
              = link_to '編集', edit_item_path(item), class: "item-list__link edit-item"
              = link_to '削除', destroy_item_path(item), method: :delete, data: { confirm: '削除しますか？' }, class: "item-list__link delete-item"
      .item-paginate
        = paginate @items


  = render './users/l-side'
= render './footer'