config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
             registrations:      'users/registrations',
             omniauth_callbacks: 'users/omniauth_callbacks' }
  root 'items#index'
  get  'items/search_brand' => 'items#search_brand'
  resources :items, only: [:index, :new, :create, :show, :edit, :update] do
    resources :orders,  only: [:new, :create]
  end
  resources :categories, only: [:index, :show]
  delete 'items/:id' => 'items#destroy', as: :destroy_item
  resources :credits, only: [:index, :new, :create, :destroy]
  resources :listings, only: [:index]
  resources :users, only: [:new] do
    resources :userconfirms, only: [:new, :create]
    resources :addresses, only: [:new, :create]
    resources :sales_moneys, only: [:index]
    get 'sales_moneys/history' => 'sales_moneys#history', as: 'sales_moneys_history'
    get 'mypage' => 'users#mypage'
    get 'profile' => 'profiles#edit'
    patch 'profile' => 'profiles#update'
  end
  get 'logout' => 'users#logout' # ログアウトボタンがある画面への遷移
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: %i[facebook google_oauth2]
  has_one :user_detail

  has_many :credits
  has_many :sales_moneys
  has_many :orders

  validates :nickname, presence: true, length: { in: 1..20 }
  validates :email, presence: true, length: { in: 4..255 }
  validates :profile, length: { maximum: 1000 }
  validates :password, presence: true, format: { with: /\A(?=.*?[a-z]{1,})[a-z\d]{6,128}+\z/i }, unless: -> { validation_context == :edit_profile }
  validates :uid, uniqueness: { scope: [:provider] }, unless: -> { validation_context == :edit_profile }

  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
    user = User.where(provider: auth.provider, uid: auth.uid).first
    unless user
      user = User.create(nickname: auth.extra.raw_info.name,
                         provider: auth.provider,
                         uid:      auth.uid,
                         email:    auth.info.email,
                         password: Devise.friendly_token[0,20]
                        )
    end
    user
  end

  def self.find_for_google_oauth2(auth, signed_in_resource=nil)
    user = User.where(provider: auth.provider, uid: auth.uid).first
    unless user
      user = User.create(nickname: auth.extra.raw_info.name,
                         provider: auth.provider,
                         uid:      auth.uid,
                         email:    auth.info.email,
                         password: Devise.friendly_token[0,20]
                        )
    end
    user
  end

  # 通常サインアップ時のuidに入れる文字列
  def self.create_unique_string
    SecureRandom.uuid
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)
    if @user.persisted?
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def google_oauth2
    @user = User.find_for_google_oauth2(request.env["omniauth.auth"], current_user)
    if @user.persisted?
      set_flash_message(:notice, :success, kind: "Google") if is_navigational_format?
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.google_oauth2_data"] = request.env["omniauth.auth"].except("extra")
      redirect_to new_user_registration_url
    end
  end

end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

  def build_resource(hash={})
    hash[:uid] = User.create_unique_string
    super
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate_user!, only: [:new]
  def new

  end

  def logout

  end

  def mypage

  end

end

app/views/users/_footer.html.haml
%aside.app-banner
  .app-banner-pc
    .app-banner-pc-inner
      %h2
        スマホでかんたんフリマアプリ
      %p
        今すぐ無料ダウンロード！
      .app-banner-icon
        %figure
          = image_tag "mercari_icon.png"
          %ul.banner
            %li
              %a{:href => "https://itunes.apple.com/jp/app/id667861049?l=ja&mt=8", :target => "_blank"}
                %img{:alt => "", :height => "40", :src => "//www-mercari-jp.akamaized.net/assets/img/common/common/app-store.svg?1700725199", :width => "133"}
            %li
              %a{:href => "https://play.google.com/store/apps/details?id=com.kouzoh.mercari&hl=ja", :target => "_blank"}
                %img{:alt => "", :height => "40", :src => "//www-mercari-jp.akamaized.net/assets/img/common/common/google-play.svg?1700725199", :width => "133"}/


    %figure
      = image_tag "cellphone.png"

%footer.global-footer
  .nav
    %ul
      %li.footer-cell
        %h2.footer-head
          メルカリについて
        %ul
          %li
            %a
              会社概要（運営会社）
          %li
            %a
              プライバシーポリシー
          %li
            %a
              メルカリ利用規約
          %li
            %a
              メルカリ利用規約・有償ポイントに関する特約
          %li
            %a
              あんしんスマホサポート制度に関する利用特約
          %li
            %a
              コンプライアンスポリシー
          %li
            %a
              個人データの安全管理に係る基本方針
          %li
            %a
              特定商取引に関する表記
          %li
            %a
              資金決済法に基づく表示
          %li
            %a
              法令順守と犯罪抑止のために
          %li
            %a
              採用情報
      %li.footer-cell
        %h2.footer-head
          メルカリを見る
        %ul
          %li
            %a
              カテゴリー一覧
          %li
            %a
              ブランド一覧
          %li
            %a
              出品地域一覧
          %li
            %a
              公式ブログ
          %li
            %a
              公式Twitter
          %li
            %a
              公式Facebook
      %li.footer-cell
        %h2.footer-head
          ヘルプ＆ガイド
        %ul
          %li
            %a
              メルカリガイド
          %li
            %a
              メルカリロゴ利用ガイドライン
          %li
            %a
              お知らせ
          %li
            %a
              らくらくメルカリ便とは
          %li
            %a
              ゆうゆうメルカリ便とは
          %li
            %a
              大型らくらくメルカリ便とは
          %li
            %a
              車体取引ガイド
          %li
            %a
              返品・返金ポリシー
          %li
            %a
              メルカリあんしん・あんぜん宣言！
          %li
            %a
              偽ブランド品撲滅への取り組み
          %li
            %a
              メルカリボックス
      %li.footer-cell
        %h2.footer-head
          国
        %ul.footer-nav-lang
          %li.usa
            %a
            %img{:alt => "", :src => "//www-mercari-jp.akamaized.net/assets/img/common/common/flag_us.png?2033025938", :width => "22"}
              United States
          %li.uk
            %a
            %img{:alt => "", :src => "//www-mercari-jp.akamaized.net/assets/img/common/common/flag_uk.png?2033025938", :width => "22"}
              United Kingdom
          %li.japan
            %a
            %img{:alt => "", :src => "//www-mercari-jp.akamaized.net/assets/img/common/common/flag_jp.png?2033025938", :width => "22"}
              日本

  %a.footer-logo
    %img{:alt => "mercari", :height => "33", :src => "//www-mercari-jp.akamaized.net/assets/img/common/common/logo-white.svg?1601456639", :width => "124"}

  %p.footer-copyright
    %small
      © 2018 Mercari

  %a.footer-sell-btn{:href => "https://www.mercari.com/jp/sell/"}
    %div
      出品
    %i.fas.fa-camera.fa-5x

app/views/users/_l-side.html.haml
.pc-header-nav-root

  .l-side
    .nav.mypage-nav
      %ul.mypage-nav-list
        %li
          = link_to user_mypage_path(current_user), class: "mypage-nav-list-item" do
            マイページ
            %i.fas.fa-angle-right
        %li
          %a.mypage-nav-list-item
            お知らせ
            %i.fas.fa-angle-right
        %li
          %a.mypage-nav-list-item
            やることリスト
            %i.fas.fa-angle-right
        %li
          %a.mypage-nav-list-item
            いいね！一覧
            %i.fas.fa-angle-right
        %li
          = link_to new_item_path, class: "mypage-nav-list-item" do
            出品する
            %i.fas.fa-angle-right
        %li
          = link_to listings_path(current_user), class: "mypage-nav-list-item" do
            出品した商品 - 出品中
            %i.fas.fa-angle-right
        %li
          %a.mypage-nav-list-item
            出品した商品 - 取引中
            %i.fas.fa-angle-right
        %li
          %a.mypage-nav-list-item
            出品した商品 - 売却済み
            %i.fas.fa-angle-right
        %li
          %a.mypage-nav-list-item
            購入した商品 - 取引中
            %i.fas.fa-angle-right
        %li
          %a.mypage-nav-list-item
            購入した商品 - 過去の取引
            %i.fas.fa-angle-right
        %li
          %a.mypage-nav-list-item
            ニュース一覧
            %i.fas.fa-angle-right
        %li
          %a.mypage-nav-list-item
            評価一覧
            %i.fas.fa-angle-right
        %li
          %a.mypage-nav-list-item
            ガイド
            %i.fas.fa-angle-right
        %li
          %a.mypage-nav-list-item
            お問い合わせ 
            %i.fas.fa-angle-right

        %h3.sales-points-label 売上・ポイント
        .mypage-nav-head
          %ul.mypage-nav-list
            %li
              = link_to user_sales_moneys_path(current_user), class: "mypage-nav-list-item" do
                売上・振込申請
                %i.fas.fa-angle-right
            %li
              %a.mypage-nav-list-item
                ポイント
                %i.fas.fa-angle-right
        %h3 設定
        .mypage-nav-head
          %ul.mypage-nav-list
            %li
              = link_to user_profile_path(current_user), { class: "mypage-nav-list-item" } do
                プロフィール
                %i.fas.fa-angle-right
            %li
              = link_to new_user_address_path(current_user), class: "mypage-nav-list-item" do
                住所変更
                %i.fas.fa-angle-right
            %li
              = link_to credits_path(current_user), class: "mypage-nav-list-item" do
                支払い方式
                %i.fas.fa-angle-right
            %li
              %a.mypage-nav-list-item
                メール/パスワード
                %i.fas.fa-angle-right
            %li
              = link_to new_user_userconfirm_path(current_user), class: "mypage-nav-list-item" do
                本人情報
                %i.fas.fa-angle-right
            %li
              %a.mypage-nav-list-item
                電話番号の確認
                %i.fas.fa-angle-right
            %li
              = link_to logout_path(current_user), class: "mypage-nav-list-item" do
                ログアウト
                %i.fas.fa-angle-right

app/views/users/_sellbtn.html.haml
%a.footer-sell-btn{:href => "https://www.mercari.com/jp/sell/"}
  %div
    出品
  %i.fas.fa-camera.fa-2x

app/views/users/logout.html.haml
.default-container
  = render './header.html.haml'
  - breadcrumb :logout
  = render './bread_crumb'
.l-container-clearfix
  .l-content
    .l-single-inner
      .l-single-content
        = link_to destroy_user_session_path, method: :delete do
          .btn-default.btn-red
            ログアウト

  = render 'l-side.html.haml'


= render './footer.html.haml'

app/views/users/mypage.html.haml
.default-container

  = render './header.html.haml'

  - breadcrumb :mypage
  = render "./bread_crumb"

.l-container-clearfix
  .right-content
    .mypage-user-icon
      %a
        %figure
          %img{:alt => "", :height => "60", :src => "//static-mercari-jp-imgtr2.akamaized.net/thumb/members/265703178.jpg?1507845787", :width => "60"}
        %h2.bold
          【衣類2枚目350円〜★】絵海
        .mypage-number
          評価
          %span.bold
            363
          出品数
          %span.bold
            339
    .mypage-tab-container-notification-todo
      %ul.mypage-tabs
        %li
          %h3.ChangeElem_Btn.is-active
            %a{"data-toggle" => "tab"}
              お知らせ

        %li
          %h3.ChangeElem_Btn
            %a{"data-toggle" => "tab"}
              やることリスト

      .tab-content
        %ul#mypage-tab-notification.mypage-item-list
          %li.ChangeElem_Panel
            %a.mypage-item-link
              %figure
                = image_tag "grey_mercari_icon.png",:size => "48x48"
              .mypage-item-body
                .mypage-item-text
                  【機能のご紹介】「いつもの説明」を簡単入力 ！テンプレート機能をぜひお試しください
                  %time
                    = fa_icon ("clock"),class: 'icon'
                    %span ３日前
                  = fa_icon ("angle-right"),class: 'icon'
          %li.ChangeElem_Panel
            %a.mypage-item-link
              %figure
                = image_tag "grey_mercari_icon.png",:size => "48x48"
              %div.mypage-item-body
                %div.mypage-item-text
                  事務局から個別メッセージ
                  %br
                  %time
                    = fa_icon ("clock"),class: 'icon'
                    %span ３日前
                  = fa_icon ("angle-right"),class: 'icon'
          %li.ChangeElem_Panel
            %a.mypage-item-link
              %figure
                = image_tag "grey_mercari_icon.png",:size => "48x48"
              .mypage-item-body
                .mypage-item-text
                  事務局から個別メッセージ
                  %br
                  %time
                    = fa_icon ("clock"),class: 'icon'
                    %span ３日前
                  = fa_icon ("angle-right"),class: 'icon'
          %li.ChangeElem_Panel
            %a.mypage-item-link
              %figure
                = image_tag "grey_mercari_icon.png",:size => "48x48"
              .mypage-item-body
                .mypage-item-text
                  事務局から個別メッセージ
                  %br
                  %time
                    = fa_icon ("clock"),class: 'icon'
                    %span ３日前
                  = fa_icon ("angle-right"),class: 'icon'
          %li.ChangeElem_Panel
            %a.mypage-item-link
              %figure
                = image_tag "grey_mercari_icon.png",:size => "48x48"
              .mypage-item-body
                .mypage-item-text
                  事務局から個別メッセージ
                  %br
                  %time
                    = fa_icon ("clock"),class: 'icon'
                    %span ３日前
                  = fa_icon ("angle-right"),class: 'icon'
          %li.mypage-go-list
            %a
              一覧を見る
        %ul#mypage-tab-notification.mypage-item-list.todo-content
          %li.ChangeElem_Panel
            %h4
              現在やることリストはありません




  %section.mypage-tab-container
    %h2.mypage-tab-head
      購入した商品
    %ul.mypage-tabs
      %li
        %h3.ChangeElem_Btn_two.is-active
          %a
            取引中
      %li
        %h3.ChangeElem_Btn_two
          %a
            過去の取引


    %div.tab-content
      %ul.mypage-item-list-two.negotiation
        %li.mypage-item-not-found
          %h3
            取引中の商品がありません
      %ul.mypage-item-list-two.old
        %li.mypage-item-old
          %figure
            = image_tag "glasses.jpg",:size => "48x48"
          .mypage-item-body
            .mypage-item-text
              %span
                「Afternoon Tea Living♥ペアグラス」を購入しました。取引が完了しました
              = fa_icon ("angle-right"),class: 'icon'
            .bold
              取引完了

        %li.mypage-item-old
          %figure
            = image_tag "bath.jpg",:size => "48x48"
          .mypage-item-body
            .mypage-item-text
              %span
                「入浴剤」を購入しました。取引が完了しました
              = fa_icon ("angle-right"),class: 'icon'
            .bold
              取引完了
  = render 'l-side.html.haml'
= render './footer.html.haml'

app/views/users/new.html.haml
.single-container
  = render partial: './subheader'
  %main.single-main
    %section.single-main__l-single-container
      %h2.single-main__l-single-container__l-single-head 新規会員登録
      .single-main__l-single-container__l-single-inner
        .l-single-content
          = link_to "/users/sign_up", class: "btn-default btn-mail" do
            %i.far.fa-envelope
            %span.registration_mail メールアドレスで登録
          %button#facebook-login.btn-default.btn-sns.btn-sns-facebook
            %i.fab.fa-facebook
            = link_to "Facebookで登録", user_facebook_omniauth_authorize_path
          %button#google-login.btn-default.btn-sns.btn-sns-google
            %i.fab.fa-google-plus-g
            = link_to "Googleで登録", user_google_oauth2_omniauth_authorize_path
  = render partial: './subfooter'