config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
             registrations:      'users/registrations',
             omniauth_callbacks: 'users/omniauth_callbacks' }
  root 'items#index'
  get  'items/search_brand' => 'items#search_brand'
  resources :items, only: [:index, :new, :create, :show, :edit, :update] do
    resources :orders,  only: [:new, :create]
  end
  resources :categories, only: [:index, :show]
  delete 'items/:id' => 'items#destroy', as: :destroy_item
  resources :credits, only: [:index, :new, :create, :destroy]
  resources :listings, only: [:index]
  resources :users, only: [:new] do
    resources :userconfirms, only: [:new, :create]
    resources :addresses, only: [:new, :create]
    resources :sales_moneys, only: [:index]
    get 'sales_moneys/history' => 'sales_moneys#history', as: 'sales_moneys_history'
    get 'mypage' => 'users#mypage'
    get 'profile' => 'profiles#edit'
    patch 'profile' => 'profiles#update'
  end
  get 'logout' => 'users#logout' # ログアウトボタンがある画面への遷移
end

app/models/item.rb
class Item < ApplicationRecord
  enum status: [:listing, :pending_delivary, :pending_recieve, :pending_evalute, :completed, :stop_listing]

  # has_many :item_comments,    dependent: :destroy
  has_many :item_images  ,    dependent: :destroy
  has_many :items_categories, dependent: :destroy
  has_many :categories, through: :items_categories
  has_many :items_sizes, dependent: :destroy
  has_many :sizes, through: :items_sizes
  # has_many :likes,        dependent: :destroy
  has_many :items_brands, dependent: :destroy
  has_many :brands, through: :items_brands
  has_many :orders
  has_many :sales_moneys
  belongs_to :user
  belongs_to :prefecture
  accepts_nested_attributes_for :item_images

  validates :item_name,    presence: true, length: { maximum: 40 }
  validates :detail,       presence: true, length: { maximum: 1000 }
  validates :ship_burden,  presence: true
  validates :ship_method,  presence: true
  validates :ship_date,    presence: true
  validates :quality,      presence: true
  validates :item_images,  presence: true, length: { maximum: 4 }
  validates :categories,   presence: true, length: { is: 3 }
  validates :sizes,        length: { is: 1 }, if: :sizes_present?
  validates :brands,       length: { maximum: 1 }
  validates :price,        presence: true, numericality: { greater_than_or_equal_to: 300,
                                                           less_than_or_equal_to: 9999999 }
  validates :status,       presence: true, inclusion: { in: Item.statuses.keys }


  scope :seller, ->(user_id,item_id) { where(user_id: user_id).where.not(id: item_id)}

  def sizes_present?
    self.sizes.present?
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :user_confirmed?,only: %i[new create update]

  def index
    @pick_up_category = Category.find([1, 2] << (3..13).to_a.sample(2))
    @pick_up_brand = Brand.find([1] << (2..Brand.count).to_a.sample(3))
    @items = Item.all.includes(:item_images).order("updated_at DESC")
  end

  def new
    @item        = Item.new
    4.times { @item.item_images.build }
    respond_to do |format|
      format.html
      format.json { @categories = Category.where(parent_id: params[:parent_id]) }
    end
  end

  def show
    @item = Item.find(params[:id])
    @items = Item.seller(@item.user_id, @item.id).limit(6).order("RAND()")
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to root_path
    else
      (4 - @item.item_images.length).times { @item.item_images.build }
      render :new
    end
  end

  def edit
    @item        = Item.find(params[:id])
    (4 - @item.item_images.length).times { @item.item_images.build }
    respond_to do |format|
      format.html
      format.json { @categories = Category.where(parent_id: params[:parent_id]) }
    end
  end

  def update
    @item = Item.find(params[:id])
    if @item.user_id == current_user.id && @item.update(update_item_params)
      redirect_to items_path
    else
      (4 - @item.item_images.length).times { @item.item_images.build }
      render :edit
    end
  end

  def destroy
    @items = Item.find(params[:id])
    if @items.destroy
      redirect_to listings_path(current_user)
    else
      flash[:notice] = '削除できませんでした'
      redirect_to listings_path(current_user)
    end
  end

  def search_brand
    @brands = Brand.where("brand_name LIKE(?)", "#{params[:keyword]}%")
    respond_to do |format|
      format.html
      format.json
    end
  end

  private
  def item_params
    params.require(:item).permit(:item_name, :detail, :price,
                                 :ship_burden,:ship_method, :ship_date,
                                 :quality, :prefecture_id, brand_ids: [],
                                 item_images_attributes: [:item_image_src],
                                 size_ids: [], category_ids: [] ).merge(status: 0, user_id: current_user.id)
  end

  def update_item_params
    params.require(:item).permit(:item_name, :detail, :price,
                                 :ship_burden,:ship_method, :ship_date,
                                 :quality, :prefecture_id, brand_ids: [],
                                 item_images_attributes: [:item_image_src, :_destroy, :id],
                                 size_ids: [], category_ids: [] ).merge(status: 0, user_id: current_user.id)
  end

  def user_confirmed?
    return true if current_user.user_detail
    redirect_to new_user_userconfirm_path(current_user.id)
  end
end

app/views/items/_itemform.html.haml
.single-container
  = render partial: "/subheader"
  .single-main
    %section.l-single-container.buy-item-container
      #sell-container
        .sell-container-inner
          %h2.l-single-head 商品の情報を入力
          - if @item.errors.any?
            - @item.errors.full_messages.each do |message|
              .error_messages= message
          = form_for @item, html:{class: 'sell-form'} do |f|
            .sell-upload-box
              %h3.sell-upload-head 出品画像
              %span.form-require 必須
              %p 最大４枚までアップロードできます
              .sell-dropbox-container
                .sell-upload-items
                  %ul
                    = f.fields_for :item_images, class: "sell-upload-drop-file", style: "none" do |image|
                      = f.label :item_image_src do
                        %li.sell-upload-drop-box.preview
                          = image.file_field :item_image_src, style: "none", class: "hidden_image_input"
            .sell-content
              .form-group
                = f.label :item_name, "商品名", class: 'form-label'
                %span.form-require 必須
                = f.text_field :item_name, class: 'input-default', placeholder: "商品名（必須 ４０字まで）"
              .form-group#product
                = f.label :detail, "商品の説明", class: 'form-label'
                %span.form-require 必須
                = f.text_area :detail, class: 'textarea-default', placeholder: "商品の説明（必須１０００字以内）（色、素材、重さ、定価、注意点など）"

            .sell-content
              %h3.sell-sub-head 商品の詳細
              .sell-form-box
                .form-group
                  = f.label :categories, "カテゴリー", class: 'form-label'
                  %span.form-require 必須
                .select_category
                  %select{ name: "item[category_ids][]", class: "select-default", id: "category" }
                    %option{ value: "" } ---
                    = Category.where(parent_id: 0).each do |category|
                      %option{ value: "#{category.id}" }
                        = category.category_name
              .sell-form-box.hidden1
                .select_category#add-category2
              .sell-form-box.hidden2
                .select_category#add-category3
              .sell-form-box.hidden3
                .form-group.size
                  = f.label :sizes, "サイズ", class: 'form-label'
                  %span.form-require 必須
                .select-wrap
                  = f.collection_select(:size_ids, Size.all, :id, :size_name, {}, { class: "select-default", name: "item[size_ids][]" })
              .sell-form-box.hidden4
                .form-group
                  = f.label :brands, "ブランド", class: 'form-label'
                  %span.form-free 任意
                %input.input-default#brand
                #add-brands-list
                = f.hidden_field :brands, name: "item[brand_ids][]", id: "brand-hidden", value: ""
              .sell-form-box.item-quality
                .form-group
                  = f.label :quality, "商品の状態", class: 'form-label'
                  %span.form-require 必須
                .select-wrap
                  = f.select :quality, [["----", "----"],["新品", "新品"], ["やや汚い", "やや汚い"],["悪い", "悪い"]],{},{class: "select-default"}

            .sell-content
              %h3.sell-sub-head 配送について
              = link_to "?", root_path, class: "question-color"
              .sell-form-box
                .form-group
                  = f.label :ship_burden, "配送料の負担", class: 'form-label'
                  %span.form-require 必須
                .select-wrap
                  = f.select :ship_burden, [["----", "----"],["送料込み", "送料込み"], ["着払い", "着払い"]],{},{class: "select-default", id: "cost"}
              .sell-form-box.hidden5
                .form-group
                  = f.label :ship_method, "配送の方法", class: 'form-label'
                  %span.form-require 必須
                .select-wrap
                  = f.select :ship_method, [["----", "----"],["らくらくメルカリ便", "らくらくメルカリ便"], ["ゆうメール", "ゆうメール"]],{},{class: "select-default"}
              .sell-form-box
                .form-group
                  = f.label :prefecture_id, "配送元の地域", class: 'form-label'
                  %span.form-require 必須
                .select-wrap
                  = f.collection_select(:prefecture_id, Prefecture.all, :id, :prefecture_name, {prompt: "---"}, { class: "select-default" })
              .sell-form-box
                .form-group
                  = f.label :ship_date, "発送までの日数", class: 'form-label'
                  %span.form-require 必須
                .select-wrap
                  = f.select :ship_date, [["----", "----"],["1~2日", "1~2日"], ["4~7日", "4~7日"]],{},{class: "select-default"}


            .sell-content
              %h3.sell-sub-head 販売価格(300~9,999,999)
              = link_to "?", root_path, class: "question-color"
              .sell-form-box
                %ul.sell-price
                  %li.form-group
                    = f.label :price, "価格", class: 'l-left'
                    %span.form-require 必須
                    = f.text_field :price, class: 'input-default', id: "amount", placeholder: "例）300"
                    .l-right
                      .sell-price-input ¥
                  %li.commission
                    .l-left 販売手数料（10％）
                    .l-right#commission  -
                  %li.profit
                    .l-left 販売利益
                    .l-right#sales-profit -


            .sell-content.sell-btn-box
              %p
                = link_to "禁止されている出品", root_path, class: "link-color"
                、
                = link_to "行為", root_path, class: "link-color"
                を必ずご確認ください。
              %p
                またブランド品でシリアルナンバー等がある場合はご記載ください。
                = link_to "偽ブランドの販売", root_path, class: "link-color"
                は犯罪であり処罰される可能性があります。
              %p
                また、出品をもちまして
                = link_to "加盟店規約", root_path, class: "link-color"
                に同意したことになります。

              = f.submit '出品する', class: 'btn-default btn-red'
              = link_to "もどる", root_path, class: "btn-default btn-gray"


  .single-footer
    = render partial: "/subfooter"

app/views/items/_new.html.haml
.single-container
  = render partial: "/subheader"
  .single-main
    %section.l-single-container.buy-item-container
      #sell-container
        .sell-container-inner
          %h2.l-single-head 商品の情報を入力
          = form_for @item, html:{class: 'sell-form'} do |f|
            .sell-upload-box
              %h3.sell-upload-head 出品画像
              %span.form-require 必須
              %p 最大４枚までアップロードできます
              .sell-dropbox-container
                .sell-upload-items
                  %ul
                    = f.fields_for :item_images, class: "sell-upload-drop-file", style: "none" do |image|
                      = f.label :item_image_src do
                        %li.sell-upload-drop-box.preview
                          = image.file_field :item_image_src, style: "none", class: "hidden_image_input"
            .sell-content
              .form-group
                = f.label :item_name, "商品名", class: 'form-label'
                %span.form-require 必須
                = f.text_field :item_name, class: 'input-default', placeholder: "商品名（必須 ４０字まで）"
              .form-group#product
                = f.label :detail, "商品の説明", class: 'form-label'
                %span.form-require 必須
                = f.text_area :detail, class: 'textarea-default', placeholder: "商品の説明（必須１０００字以内）（色、素材、重さ、定価、注意点など）"

            .sell-content
              %h3.sell-sub-head 商品の詳細
              .sell-form-box
                .form-group
                  = f.label :categories, "カテゴリー", class: 'form-label'
                  %span.form-require 必須
                .select_category
                  %select{ name: "item[category_ids][]", class: "select-default", id: "category" }
                    %option{ value: "" } ---
                    = Category.where(parent_id: 0).each do |category|
                      %option{ value: "#{category.id}" }
                        = category.category_name
              .sell-form-box.hidden1
                .select_category#add-category2
              .sell-form-box.hidden2
                .select_category#add-category3
              .sell-form-box.hidden3
                .form-group.size
                  = f.label :sizes, "サイズ", class: 'form-label'
                  %span.form-require 必須
                .select-wrap
                  = f.collection_select(:size_ids, Size.all, :id, :size_name, {}, { class: "select-default", name: "item[size_ids][]" })
              .sell-form-box.hidden4
                .form-group
                  = f.label :brands, "ブランド", class: 'form-label'
                  %span.form-free 任意
                %input.input-default#brand
                #add-brands-list
                = f.hidden_field :brands, name: "item[brand_ids][]", id: "brand-hidden", value: ""
              .sell-form-box.item-quality
                .form-group
                  = f.label :quality, "商品の状態", class: 'form-label'
                  %span.form-require 必須
                .select-wrap
                  = f.select :quality, [["----", "----"],["新品", "新品"], ["やや汚い", "やや汚い"],["悪い", "悪い"]],{},{class: "select-default"}

            .sell-content
              %h3.sell-sub-head 配送について
              = link_to "?", root_path, class: "question-color"
              .sell-form-box
                .form-group
                  = f.label :ship_burden, "配送料の負担", class: 'form-label'
                  %span.form-require 必須
                .select-wrap
                  = f.select :ship_burden, [["----", "----"],["送料込み", "送料込み"], ["着払い", "着払い"]],{},{class: "select-default", id: "cost"}
              .sell-form-box.hidden5
                .form-group
                  = f.label :ship_method, "配送の方法", class: 'form-label'
                  %span.form-require 必須
                .select-wrap
                  = f.select :ship_method, [["----", "----"],["らくらくメルカリ便", "らくらくメルカリ便"], ["ゆうメール", "ゆうメール"]],{},{class: "select-default"}
              .sell-form-box
                .form-group
                  = f.label :prefecture_id, "配送元の地域", class: 'form-label'
                  %span.form-require 必須
                .select-wrap
                  = f.collection_select(:prefecture_id, Prefecture.all, :id, :prefecture_name, {prompt: "---"}, { class: "select-default" })
              .sell-form-box
                .form-group
                  = f.label :ship_date, "発送までの日数", class: 'form-label'
                  %span.form-require 必須
                .select-wrap
                  = f.select :ship_date, [["----", "----"],["1~2日", "1~2日"], ["4~7日", "4~7日"]],{},{class: "select-default"}


            .sell-content
              %h3.sell-sub-head 販売価格(300~9,999,999)
              = link_to "?", root_path, class: "question-color"
              .sell-form-box
                %ul.sell-price
                  %li.form-group
                    = f.label :price, "価格", class: 'l-left'
                    %span.form-require 必須
                    = f.text_field :price, class: 'input-default', id: "amount", placeholder: "例）300"
                    .l-right
                      .sell-price-input ¥
                  %li.commission
                    .l-left 販売手数料（10％）
                    .l-right#commission  -
                  %li.profit
                    .l-left 販売利益
                    .l-right#sales-profit -


            .sell-content.sell-btn-box
              %p
                = link_to "禁止されている出品", root_path, class: "link-color"
                、
                = link_to "行為", root_path, class: "link-color"
                を必ずご確認ください。
              %p
                またブランド品でシリアルナンバー等がある場合はご記載ください。
                = link_to "偽ブランドの販売", root_path, class: "link-color"
                は犯罪であり処罰される可能性があります。
              %p
                また、出品をもちまして
                = link_to "加盟店規約", root_path, class: "link-color"
                に同意したことになります。

              = f.submit '出品する', class: 'btn-default btn-red'
              = link_to "もどる", root_path, class: "btn-default btn-gray"


  .single-footer
    = render partial: "/subfooter"

app/views/items/create.html.haml
%h1 Items#create

app/views/items/edit.html.haml
= render partial: "itemform"

app/views/items/index.html.haml
= render './header'
.wrapper
  .slide-box
    %ul.slider
      %li.slider__list
        .slider__list--image1
      %li.slider__list
        .slider__list--image2
      %li.slider__list
        .main-banner
          .main-banner-content
            .main-banner-text
              %h1.main-banner-text__title スマホでかんたんフリマアプリ
              %p.main-banner-text__detail
                メルカリはスマホアプリからすぐに出品できる
                %br
                購入時も安心な独自システムのアプリです
              .main-banner-link
                = image_tag 'app-store.svg',   size: "170x50"
                = image_tag 'google-play.svg', size: "170x50"
            = image_tag 'main_content_pc.png', class: "main-banner-content__image"
  .main-content
    .pick-up-container
      %h2.pick-up-container__title ピックアップカテゴリー
      - @pick_up_category.each do |category|
        .pick-up
          /TODO カテゴリの商品一覧へリンク
          = link_to "#", class: "pick-up__category" do
            = category.category_name
            新着アイテム
          .item-boxes
            - category.items.order("updated_at DESC").limit(4).each do |item|
              .item-box
                = link_to item_path(item) do
                  - unless item.status == "listing"
                    .sold-text SOLD
                    .sold-box
                  %img{ src: "#{item.item_images[0].item_image_src}", class: "item-box-image" }
                  .item-box-content
                    %h4.item-box-content__name= item.item_name
                    .item-info
                      .price-box
                        %p.price-box__price
                          = item.price.to_s(:currency, unit: "¥", precision: 0)
                        %p.price-box__tax (税込)
                      .likes-box
                        %i{ class: "far fa-heart" }
                        /TODO item.likes.count
                        %span 10
          .pick-up__view-all
            /TODO カテゴリの商品一覧へリンク
            = link_to "すべての商品を見る", "#"
    .pick-up-container
      %h2.pick-up-container__title ピックアップブランド
      - @pick_up_brand.each do |brand|
        .pick-up
          = link_to "#", class: "pick-up__category" do
            = brand.brand_name
            新着アイテム
          .item-boxes
            - brand.items.order("updated_at DESC").limit(4).each do |item|
              .item-box
                = link_to item_path(item) do
                  - unless item.status == "listing"
                    .sold-text SOLD
                    .sold-box
                  %img{ src: "#{item.item_images[0].item_image_src}", class: "item-box-image" }
                  .item-box-content
                    %h4.item-box-content__name= item.item_name
                    .item-info
                      .price-box
                        %p.price-box__price
                          = item.price.to_s(:currency, unit: "¥", precision: 0)
                        %p.price-box__tax (税込)
                      .likes-box
                        %i{ class: "far fa-heart" }
                        %span 10
          .pick-up__view-all
            = link_to "すべての商品を見る", "#"

= render './footer'
%script{src: "https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.9.0/slick.min.js", type: "text/javascript"}
= javascript_include_tag 'items/index.js'

app/views/items/new.html.haml
= render partial: "itemform"

app/views/items/show.html.haml
.container
  = render './header.html.haml'
  = render './bread_crumb'
  .default-container
    %section.item-box-container.l-single-container
      %h1.item-name
        = @item.item_name
      .item-main-content.clearfix
        .item-photo
          .owl-carousel.owl-loaded.owl-drag
            .owl-stage-outer
              .owl-stage
                .owl-item.active
                  .owl-item-inner
                    - @item.item_images.each do |item_image|
                      = image_tag "#{item_image.item_image_src}", size: "300x300", id: "main_image"
                .owl-item
                  .owl-item-inner
                .owl-item
                  .owl-item-inner.is-higher-width
                .owl-item
                  .owl-item-inner.is-higher-width
            .owl-nav.disabred
            .owl-dots
              - @item.item_images.limit(4).each do |item_image|
                .owl-dot
                  %span
                  .owl-dot-inner
                    = image_tag "#{item_image.item_image_src}", size: "75x75", class: "owl"

        .item-price-box.text-center.visible-sp
          %span.item-price
          %span.item-tax
          %span.item-shipping-fee
        %section.visible-sp
          %a.item-buy-btn.f18-24

        %table.item-detail-table
          %tbody
            %tr
              %th 出品者
              %td
                = link_to user_mypage_path(@item.user_id) do
                  = @item.user.nickname
                %div
                  .item-user-ratings
                    = fa_icon 'smile', class: "smile"
                    %span 536
                  .item-user-ratings
                    = fa_icon 'meh', class: "meh"
                    %span 20
                  .item-user-ratings
                    = fa_icon 'frown', class: "bad"
                    %span 3
            %tr
              %th カテゴリー
              %td
                %a
                - @item.categories.where(parent_id: 0).each do |category|
                  = category.category_name
                %a
                  .item-detail-table-sub-category
                    = fa_icon 'angle-right', class: "right"
                    - @item.categories.where(parent_id: 1..13).each do |category|
                      = category.category_name
                %a
                  .item-detail-table-sub-sub-category
                    = fa_icon 'angle-right', class: "right"
                    - @item.categories.where(parent_id: 14..166).each do |category|
                      = category.category_name
            %tr
              %th ブランド
              - if @item.brands.present?
                - @item.brands.each do |brand|
                  %td #{brand.brand_name}
            %tr
              %th 商品の状態
              %td
                = @item.quality
            %tr
              %th 配送料の負担
              %td
                = @item.ship_burden
            %tr
              %th 配送の方法
              %td
                = @item.ship_method
            %tr
              %th 配送元地域
              %td
                = link_to "#" do
                  = @item.prefecture.prefecture_name
            %tr
              %th 発送日の目安
              %td
                = @item.ship_date

      .item-price-box.text-center
        %span.item-price
          = @item.price.to_s(:currency, unit: "¥", precision: 0)
        %span.item-tax (税込)
        %span.item-shipping-fee 送料込み
      - if @item.status == "listing"
        = link_to "購入画面に進む", new_item_order_path(@item), class: "item-buy-btn f18-24"
      - else
        .item-buy-btn.sold 売り切れました
      .item-description.f14
        %p.item-description-inner
          = @item.detail

      .item-button-container.clearfix
        .item-button-left
          %a.item-button.item-button-like
            = fa_icon 'heart'
            %span いいね!
            %span 13
          %a.item-button.item-button-report.clearfix
            = fa_icon 'flag'
            %span 不適切な商品の報告
        .item-button-right
          .description-page
            = link_to "#" do
              = fa_icon 'lock'
              %span あんしん・あんぜんへの取り組み

.item-detail-message
  .message-container
    %form.message-form
      %p 相手のことを考え丁寧なコメントを心がけましょう。不快な言葉遣いなどは利用制限や退会処分となることがあります。
      %textarea.textarea-default
      %button.message-submit.btn-default.btn-gray
        %span コメントする
%ul.nav-detail-item.clearfix
  %li.nav-item-link-prev
    %a
      = fa_icon 'angle-left', class: 'lock-icon'
      VANS スニーカー
  %li.nav-item-link-next
    %a
      ATSUGIフラワードット側ストッキング
      = fa_icon 'angle-right', class: 'lock-icon'
.item-social-media-box
  %ul.social-media-box
    %li
      %a
        = fa_icon 'facebook-square' , class: 'sns-icon facebook-icon'
    %li
      %a
        = fa_icon 'twitter' , class: 'sns-icon twitter-icon'
    %li
      %a
        = fa_icon 'pinterest-square' , class: 'sns-icon pinterest-icon'
.item-in-user-profile
  .items-profile.items-box-content.clearfix
    %h2.items-box-head.bold
      = link_to "#", class: 'user-page-pro' do
        #{@item.user.nickname}さんのその他の出品
        .item-boxes
          .item-box
            - @items.each do |item|
              = link_to item_path(item) do
                = image_tag "#{item.item_images[0].item_image_src}", size: "220x220"
                .item-box-content
                  %h4.item-box-content__name
                    = item.item_name
                  .item-info
                    .price-box
                      %p.price-box__price
                        = item.price.to_s(:currency, unit: "¥", precision: 0)
                      %p.price-box__tax (税込)
                    .likes-box
                      = fa_icon 'heart'
                      %span 100




= render './footer.html.haml'