config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
             registrations:      'users/registrations',
             omniauth_callbacks: 'users/omniauth_callbacks' }
  root 'items#index'
  get  'items/search_brand' => 'items#search_brand'
  resources :items, only: [:index, :new, :create, :show, :edit, :update] do
    resources :orders,  only: [:new, :create]
  end
  resources :categories, only: [:index, :show]
  delete 'items/:id' => 'items#destroy', as: :destroy_item
  resources :credits, only: [:index, :new, :create, :destroy]
  resources :listings, only: [:index]
  resources :users, only: [:new] do
    resources :userconfirms, only: [:new, :create]
    resources :addresses, only: [:new, :create]
    resources :sales_moneys, only: [:index]
    get 'sales_moneys/history' => 'sales_moneys#history', as: 'sales_moneys_history'
    get 'mypage' => 'users#mypage'
    get 'profile' => 'profiles#edit'
    patch 'profile' => 'profiles#update'
  end
  get 'logout' => 'users#logout' # ログアウトボタンがある画面への遷移
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :items_categories, dependent: :destroy
  has_many :items, through: :items_categories
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
    @items = Category.find(params[:id]).items.order("created_at DESC").page(params[:page]).per(20)
  end


end

app/views/categories/index.html.haml
.container
  = render './header.html.haml'

  - breadcrumb :category
  = render './bread_crumb'


  .category-index_container
    .category-index_title
      %h1.title カテゴリー一覧
    %ul.category-list-nav
      - @categories.where("parent_id = 0").each do |category|
        %li.category-list-nav_li
          = link_to "#{category.category_name}", "##{category.id}", class: "category-list-nav_li__name"

    .category-list-box
      - @categories.where("parent_id = 0").each do |category1|
        .category-list-individual-box{ id: category1.id }
          .category-list-individual-box__name
            %h2.root_category= category1.category_name
          .category-list-individual-box__inner-box
            = link_to 'すべて', category_path(category1), class: "all"
            - @categories.where(parent_id: category1.id).each do |category2|
              .category-sub-category-name
                %h4.category-2= category2.category_name
                .category-sub-sub-category-box
                  %ul.category-3-list
                    - @categories.where(parent_id: category2.id).each do |category3|
                      %li.category-3-list__li
                        = link_to "#{category3.category_name}", category_path(category3), class: "category-3"







= render './footer.html.haml'

app/views/categories/show.html.haml
.container
  = render './header.html.haml'
  - breadcrumb :category_list, @category
  = render './bread_crumb'


  .main-container
    .main-container_full-width
      .categories-items-box-container
        %h1.items-box-head
          = @category.category_name + "の商品一覧"
        .category-brand-list
          .item-boxes
            .category-item-box
              - @items.each do |item|
                = link_to item_path(item) do
                  - unless item.status == "listing"
                    .sold-text SOLD
                    .sold-box
                  = image_tag "#{item.item_images[0].item_image_src}", size: "220x220"
                  .item-box-content
                    %h4.item-box-content__name #{item.item_name}
                    .item-info
                      .price-box
                        %p.price-box__price
                          = item.price.to_s(:currency, unit: "¥", precision: 0)
                        %p.price-box__tax (税込)
                      .likes-box
                        %i{ class: "far fa-heart" }
                        %span 10

        .item-paginate
          = paginate @items



= render './footer.html.haml'